# Generated by Django 6.0.2 on 2026-03-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
