# Generated by Django 6.0.2 on 2026-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visitor_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
